#!/bin/sh
set -e

EXIT_OK=0
EXIT_USAGE=1
EXIT_FAILURE=2
# EXIT_RETRY=3

usage() {
    cat << EOF
USAGE
    apk plugin for thin-edge.io

    $0 <COMMAND> [MODULE_NAME] [--module-version [VERSION]] [--file [FILE]]

    $0 list
    $0 prepare
    $0 install <MODULE_NAME> [--module-version [VERSION]] [--file [FILE]]
    $0 remove <MODULE_NAME> [--module-version [VERSION]]
    $0 finalize
EOF
}

MODULE_NAME=
MODULE_VERSION=
FILE=

log() { echo "$@" >&2; }

if [ $# -lt 1 ]; then
    log "Invalid number of positional arguments"
    usage
    exit "$EXIT_USAGE"
fi

# argument parsing
while [ $# -gt 0 ]; do
  case "$1" in
    --module-version)
        MODULE_VERSION="$2"
        shift
        ;;
    --file)
        FILE="$2"
        shift
        ;;
    -h|--help)
        usage
        exit "$EXIT_USAGE"
        ;;
    --*|-*)
        log "Unknown option $1"
        exit "$EXIT_USAGE"
        ;;
    *)
        if [ -z "$COMMAND" ]; then
            COMMAND="$1"
        elif [ -z "$MODULE_NAME" ]; then
            MODULE_NAME="$1"
        fi
      ;;
  esac
  shift
done

case "$COMMAND" in
    prepare)
        apk update
        ;;
    list)
        # TODO: ill formed packages that don't use the -R0 revision mixed the name with the version:
        # tedge-apk-plugin-0.0.0rc0 noarch {tedge-apk-plugin} (Apache License 2.0) [installed]
        apk list --installed | cut -d' ' -f1 | rev | sed 's/-/:/' | sed 's/-/\t/' | sed 's/:/-/' | rev || exit "$EXIT_FAILURE"
        # Make sure perl is installed
        # apk list | cut -d' ' -f1 | sed 's|\(.*\)-\(.*-.*\)$|\1\t\2|g' || exit 2
        ;;
    install)
        if [ -n "$FILE" ]; then
            log "Installing from file: $FILE"
            # apk requires the file to have an .apk extension
            ln -sf "$FILE" "$FILE.apk"
            apk add --allow-untrusted "$FILE.apk" || exit "$EXIT_FAILURE"
            rm -f "$FILE.apk"
        else
            MODULE="$MODULE_NAME"
            if [ -n "$MODULE_VERSION" ] && [ "$MODULE_VERSION" != "latest" ]; then
                MODULE="${MODULE_NAME}=${MODULE_VERSION}"
            fi

            log "Installing: $MODULE"
            apk add "$MODULE" || exit "$EXIT_FAILURE"
        fi
        ;;
    remove)
        # Removing
        apk del "$MODULE_NAME" || exit "$EXIT_FAILURE"
        ;;
    update-list)
        # Not supported, use remove install and remove instead
        exit "$EXIT_USAGE"
        ;;
    finalize)
        ;;
    *)
        log "Unsupported command: $COMMAND"
        exit 1
        ;;
esac
